### ISSUE TITLE
Extraneous files in Spring folder

### ISSUE THREAD

**Issue by imkevinxu** [MengTo/Spring#10]
There seem to be a lot of extraneous files in the `Spring` folder like `Data.swift` and `Info.plist` or `LoadingView.xib` and I'm not sure what is absolutely necessary for Spring to run while integrated with my project. Could you look into separating the absolutely necessary files for animation vs the demo app? Thanks!

**Comment by MengTo** [comment]
You're right, they're remnants of the chapter 4 files for beginners to get started. I'll put them in a different folder and do a cleanup!




Thanks! Meng

**Comment by imkevinxu** [comment]
Actually I just took a deeper look into some of the files and they're pretty useful actually! Maybe add some documentation on them :)

**Comment by MengTo** [comment]
Thanks, will definitely give some more thought on the organization of the package and document the extra utilities more. Feel free to contribute. :)
