### ISSUE TITLE
How can I do something after animation finish?

### ISSUE THREAD

**Issue by eflyjason** [MengTo/Spring#102]
Here's my code:

```
innerUILabel.animation = "fall"
innerUILabel.curve = "easeIn"
innerUILabel.duration = 1.5
innerUILabel.animate()
innerUILabel.removeFromSuperview()
```

I want to `removeFromSuperview()` after animation finished. How can i do that? Thanks!

**Comment by lastMove** [comment]
just call 
innerUILabel.animateNext() { innerUILabel.removeFromSuperview() }
