### ISSUE TITLE
SpringButton do not animate in second time tapped

### ISSUE THREAD

**Issue by LadyRanger1992** [MengTo/Spring#108]
//this is my code:
#import "MyProject-Swift.h"
SpringButton* buyLate = [[SpringButton alloc] initWithFrame:CGRectMake(xPos, frame.size.height - WIDTH*0.12, WIDTH*0.4333, WIDTH*0.1)];
    [buyLate setBackgroundColor:[UIColor LVL_colorWithHexString:@"313131" andAlpha:1.0]];
    buyLate.animation = @"squeeze";
    buyLate.curve = @"linear";
    [buyLate addTarget:self action:@selector(buyLateTapped:) forControlEvents:UIControlEventTouchUpInside];
    [self.view addSubview:buyLate];

// and in the buyLateTapped function
-(void)buyLateTapped:(id)sender
{
    SpringButton* btn = (SpringButton*)sender;
    [btn animate];
   //do some thing....
}
the SpringButton only animate in first time. What happen with my code? and how to resolved this problem?
Thank you

**Comment by lastMove** [comment]
it the normal behavior.
when you configure animation curve etc it reset to 0 after calling "[btn animate]" 
So you just have to write that code inside your IBAction method:

-(void)buyLateTapped:(SpringButton*)btn
{
btn.animation = @"squeeze";
btn.curve = @"linear";
[btn animate];
}
hope it helps

**Comment by LadyRanger1992** [comment]
Oh, thank you very much !
So it mean each time we make the animation, all attribute will be reset?.
