### ISSUE TITLE
How do you use KeyboardLayoutConstraint in IB?

### ISSUE THREAD

**Issue by dincho** [MengTo/Spring#109]
I'm sorry if this is RTFM question, but I can't find any documentation of using this constraint. Can I use it as standalone class, or I need the full framework for some reason?

**Comment by jamztang** [comment]
It is part of the building blocks for the DesignerNewsApp, but technically it should be clean enough to used standalone.

**Comment by dincho** [comment]
Indeed it works. http://stackoverflow.com/a/28265303/3967231

**Comment by jamztang** [comment]
Awesome :) Thanks for pointing to the sample solution
