### ISSUE TITLE
Carthage support

### ISSUE THREAD

**Issue by raulriera** [MengTo/Spring#11]
Supporting Cocoapods (http://cocoapods.org) and/or Carthage (https://github.com/Carthage/Carthage) is great for libraries. It might not be the easiest thing for "new comers", but for the rest is a must

**Comment by MengTo** [comment]
Definitely working on this! :D

**Comment by clooth** [comment]
I manage to get it working with Carthage by setting the Spring.framework's scheme as shared in Xcode and then tagging the version on my fork of Spring. (https://github.com/clooth/Spring/tree/1.0.1)

**Comment by jamztang** [comment]
The merge is going well to have Carthage recognise and build the framework correctly.

However, I had issues with integrating this way is that SpringView's IBInspectable are not correctly showing up in the view properties panel. Classes are also not auto filled when I typed into the custom class textfield on a view. Anyone had some pointers?

**Comment by raulriera** [comment]
This merge is not in the master branch right? I get a `Project "SpringApp.xcodeproj" has no shared schemes` error when trying to use it

**Comment by schneiderandre** [comment]
@raulriera yes, the ```1.0.0``` tag was created before #13 was merged.
I'm not sure why Carthage uses tag ```1.0.1``` for me, but this works. I'll talk to @jamztang and @MengTo and we will either move the tag or create a new one.

**Comment by jamztang** [comment]
I'll move 1.0.0 from 9ac47a4 to 490a266

**Comment by raulriera** [comment]
You are correct, they don't show up in the properties inspector, nor they autocomplete in the Custom Class section of a view, but they do show in the code normally if I `import Spring`

Might be an issue with Carthage?

**Comment by jamztang** [comment]
Thanks for filing an issue on Carthage. Yeah we didn't have the same problem with other Integration methods, have you seen projects works with IB correctly using Carthage?

**Comment by raulriera** [comment]
Not at the moment no, the two I put in there are the only UI ones I have seen so far

**Comment by jamztang** [comment]
Right, thanks @raulriera, we'll keep an eye on the Carthage issue and see what we can do!

**Comment by raulriera** [comment]
After some testing out I noticed that the framework is stripping out the initialisers from classes and this is why they are not accessible via Storyboard. 

For my project, if you do a Carthage (or a normal framework build) and then import the framework into any project, CMD + clicking into the `import yourFramework` shows you the lists of methods available, and some of the initialisers disappeared.

I am unable to solve this on my own project, but maybe this can give you some idea

**Comment by jamztang** [comment]
That sounds like a good hint, thanks @raulriera. We'll come back to this.

**Comment by schneiderandre** [comment]
I tried it again in Xcode Version 6.4 (6E35b) with Carthage and also with a manual Framework Build, but it seems that the issues with the Designables/Inspectables in embedded Binaries still exist.

**Comment by raulriera** [comment]
Yes, this bug persists in Xcode 7 I opened this (but for real on Apple's) http://www.openradar.me/radar?id=5031199516917760 and it was marked as duplicate.. so at least someone looked at it

**Comment by schneiderandre** [comment]
Thanks for the update :+1:, good to hear that they are aware of this.

**Comment by schneiderandre** [comment]
I will close this for now, since it sounds like an Xcode issue :disappointed:.
Feel free to reopen this if you have any new insights.
