### ISSUE TITLE
Xcode 7 Beta (for iOS9) - Errors when Importing Spring folder or Cocopods Into Project

### ISSUE THREAD

**Issue by jried31** [MengTo/Spring#113]
Great framework. Following your designcode tutorial using Xcode 7 Beta for Prototyping screens. When I import the Spring framework via drag/drop or Cocoapods, I get many class errors. I've tried to correct some of them but many are not easily debuggable. Attached a screenshot of some.

![screen shot 2015-08-26 at 12 32 49 pm](https://cloud.githubusercontent.com/assets/372923/9503924/a50342b2-4bee-11e5-959b-4175bb082343.png)

**Comment by MengTo** [comment]
Make sure to download the latest beta and the swift2 branch. https://github.com/mengto/spring/tree/swift2

**Comment by jried31** [comment]
Your the man! Works great :) Thanks for your help.
