### ISSUE TITLE
Minimum Deployment Target is iOS 9

### ISSUE THREAD

**Issue by orangecoding** [MengTo/Spring#116]
Hey,

if I use your Swift 2 Branch, the minimum Deployment Target is iOS which is ridiculous. Most of the users still depending on iOS 8. Could you please change this?

Thanks.

**Comment by MengTo** [comment]
Thanks for mentioning. I'll see what I can do to support iOS 8!




Thanks! Meng

**Comment by orangecoding** [comment]
Thanks. I guess it's not really useful to limit this awesome lib to the news OS. You would actually cut out a lot of users that can't update.

**Comment by MengTo** [comment]
I tried to import Spring in a new project and I could still build using a deployment target of iOS 8. Can you point out the requirement for iOS 9?

**Comment by juliengdt** [comment]
I confirm it builds with iOS8 . no need to be in iOS 9 ...

**Comment by MengTo** [comment]
Thanks for confirming, I'll close this issue.
