### ISSUE TITLE
Can't connect Spring on XCode 7.0

### ISSUE THREAD

**Issue by adooone** [MengTo/Spring#119]
Hi,
I'm new to coding so sorry in advance for the silly questions.

I started a new project and i added the Spring file to the project then i created a simple view and i tried to add rounded corners but the class won't connect to the project. I attached an image of what i'm getting.

![spring2](https://cloud.githubusercontent.com/assets/14984846/10291200/7fb3324a-6b5d-11e5-9af9-68f01f71a60a.png)

![spring](https://cloud.githubusercontent.com/assets/14984846/10291181/58acd408-6b5d-11e5-90d9-5a91641126ba.png)

**Comment by MengTo** [comment]
You simply didn't install Spring correctly. Make sure to enable "Copy items if needed"
<img width="730" alt="xcode" src="https://cloud.githubusercontent.com/assets/1065452/10291630/d84c8d1e-6b78-11e5-9eb5-0ca2ab71f75c.png">
 and "Make groups".

**Comment by adooone** [comment]
Thanks for the quick reply.

I connected Spring successfully thanks to your tip but the project still shows a build fail message. I started a new project but i'm still getting the same error message (Pictures attached)
![spring3](https://cloud.githubusercontent.com/assets/14984846/10297832/d246149e-6b8c-11e5-9be0-a71ad796b10c.png)
![spring4](https://cloud.githubusercontent.com/assets/14984846/10297833/d2481a96-6b8c-11e5-84f2-08c108d65e32.png)

**Comment by MengTo** [comment]
This simply means that you downloaded the wrong version of Spring. Make sure that you have Xcode 7.0.1 and the latest version of Spring: https://github.com/MengTo/Spring/archive/master.zip

**Comment by adooone** [comment]
I downloaded the latest version of Spring and i updated my XCode to 7.0.1 and everything Is working perfectly, thank you very much for your help.

**Comment by MengTo** [comment]
Great to hear!
