### ISSUE TITLE
[RESOLVED] UIButton Swing Animation Not Working

### ISSUE THREAD

**Issue by acegreen** [MengTo/Spring#131]
Hi 

I have my UIButton hidden initially and I just unhide it when needed. setting the animation programatically does not work for "swing"

        rewardsButton.hidden = false
        rewardsButton.animation = "swing"
        rewardsButton.repeatCount = 1000
        rewardsButton.animate()

Though for the exact same button it works with shake. 

Also wobble and shake do the exact same thing or?

**Comment by acegreen** [comment]
So I think I got swing working but the repeatCount has no effect. 
That means it only animates once

        starButton.animation = "fadeIn"
        starButton.animateNext {
            self.starButton.animation = "swing"
            self.starButton.repeatCount = 1000
            self.starButton.animate()

**Comment by acegreen** [comment]
Figured out the repeatCount issue:

Your .Swing case was missing it:

            case .Swing:
                let animation = CAKeyframeAnimation()
                animation.keyPath = "transform.rotation"
                animation.values = [0, 0.3*force, -0.3*force, 0.3*force, 0]
                animation.keyTimes = [0, 0.2, 0.4, 0.6, 0.8, 1]
                animation.duration = CFTimeInterval(duration)
                animation.additive = true
                animation.repeatCount = repeatCount
                animation.beginTime = CACurrentMediaTime() + CFTimeInterval(delay)
                layer.addAnimation(animation, forKey: "swing")
            }

**Comment by phatmann** [comment]
@acegreen Did you submit this change as a pull request?

**Comment by alexandercyr** [comment]
Ah! This saved me. Thank you! Had the same issue with "wobble" where it would play the wobble anim and then start doing a "shake" animation.
