### ISSUE TITLE
Xcode doesn't recognize Spring, and Build failed. Any idea?

### ISSUE THREAD

**Issue by RudyRosciglione** [MengTo/Spring#133]
Well. i posted first on the design + code facebook group but i seen mostly design post. And i need dev-help. Indeed. I started to develop Pancake my application, anyway, The problem is simple. Spring doesn't work. I did all the step right as the video. But nothing happen. Does it because of some software update. Sound like Xcode doesn't recognized Spring.. next to the Spring file on the left-side there is a question mark. I hope you would be able to help me.

<img width="1440" alt="screen shot 2015-12-09 at 15 13 52" src="https://cloud.githubusercontent.com/assets/1166152/11687916/c4814b78-9e89-11e5-9ec2-c59ac54ca536.png">
<img width="1440" alt="screen shot 2015-12-09 at 15 13 57" src="https://cloud.githubusercontent.com/assets/1166152/11687917/c483f2f6-9e89-11e5-93e5-60bd208fd272.png">
<img width="1440" alt="screen shot 2015-12-09 at 15 14 06" src="https://cloud.githubusercontent.com/assets/1166152/11687918/c48cadce-9e89-11e5-8118-f3e559b031a1.png">
<img width="1440" alt="screen shot 2015-12-09 at 15 14 18" src="https://cloud.githubusercontent.com/assets/1166152/11687919/c48fface-9e89-11e5-9106-531ba9bb05dc.png">
<img width="1440" alt="screen shot 2015-12-09 at 15 14 37" src="https://cloud.githubusercontent.com/assets/1166152/11687921/c49e522c-9e89-11e5-9658-35f409105d92.png">
<img width="1440" alt="screen shot 2015-12-09 at 15 14 47" src="https://cloud.githubusercontent.com/assets/1166152/11687920/c49d845a-9e89-11e5-9cc8-dc082bf04245.png">
<img width="1440" alt="screen shot 2015-12-09 at 15 14 54" src="https://cloud.githubusercontent.com/assets/1166152/11687922/c4a99bf0-9e89-11e5-9c0b-cef81ef59964.png">
<img width="1440" alt="screen shot 2015-12-09 at 15 15 07" src="https://cloud.githubusercontent.com/assets/1166152/11687923/c4ac5f66-9e89-11e5-9628-ae1d6e0badd1.png">
<img width="1440" alt="screen shot 2015-12-09 at 15 26 51" src="https://cloud.githubusercontent.com/assets/1166152/11687924/c4b629f6-9e89-11e5-854b-aa0f10948218.png">
<img width="1440" alt="screen shot 2015-12-09 at 15 26 53" src="https://cloud.githubusercontent.com/assets/1166152/11687925/c4b97a48-9e89-11e5-8c5e-9b933f1271c4.png">

**Comment by acegreen** [comment]
Did you try cocoapods? worked great for me

**Comment by RudyRosciglione** [comment]
I didn't try it. But i also don't know how to use it.

**Comment by RudyRosciglione** [comment]
DO NOT INSTALL THE " SPRING-MASTER" BUT INSTALL THE "SPRING" WHICH IS IN THE SPRING-MASTER FILE. ;)
