### ISSUE TITLE
Possible retain Cycle?

### ISSUE THREAD

**Issue by camitox** [MengTo/Spring#16]
Hi!,

Please correct me if I'm wrong.

I'm looking at your SpringButton:

`    lazy private var spring : Spring = Spring(self)`

and the Spring:

```
    private var view : Springable

    init(_ view: Springable) {
        self.view = view
    }
```

Won't this be a retain cycle, preventing to release the button from memory?

**Comment by 0oneo** [comment]
```
public class Spring : NSObject {

    private unowned var view : Springable

    init(_ view: Springable) {
        self.view = view
    }
```

**Comment by jamztang** [comment]
Thanks! Merged.
