### ISSUE TITLE
Animation run only one time when applied in TabViewController's child viewcontrollers via Storyboard?

### ISSUE THREAD

**Issue by Elgins** [MengTo/Spring#190]
I set the views with Spring animation via Storyboard which the ViewController is in the TabViewContoller, but I switch between different viewControllers, the animation commit only once when first time switch to it. Anyone no why? Pleas help me out!

**Comment by az3r** [comment]
do it in code, check closed issues and you'll find couple of answers similar to yours.

**Comment by Elgins** [comment]
Ok, thanks too much pal. I'll check it.
