### ISSUE TITLE
New 'open' Access control in Swift 3.0

### ISSUE THREAD

**Issue by SRowley90** [MengTo/Spring#197]
New 'open' Access control in Swift 3.0 is needed instead of 'public' for the various SpringViews in order for them to be inherited from. Or you get the following error:

`Overriding non-open instance method outside of its defining module`

Would submit the change myself but have never contributed on GitHub before and have no idea how to go about it properly.

**Comment by MengTo** [comment]
Do you have some documentation on this or can you explain more? I'm getting no warnings for this.

**Comment by Freak5M** [comment]
Hi :)
 
Here is a [documentation](https://github.com/apple/swift-evolution/blob/master/proposals/0117-non-public-subclassable-by-default.md) about this Swift  3 evolution.

To sum up, for this "issue", it all deals with overriding.
Let's imagine you want to define a custom class `MyDesignableButton` with all base behavior from `DesignableButton`
As `DesignableButton` is declared public in Spring module it can only be "overrided" in it's own module. By changing this to `open`, you can override it in any module of your project.

**Comment by SRowley90** [comment]
In before me but yeah that's pretty much it. In my project I have a few things that inherit from classes within Spring which are no longer valid unless they are declared open. Thanks Freak5M

**Comment by MengTo** [comment]
Thanks Freak5M for the explanation. That makes sense. Just merged.
