### ISSUE TITLE
Replace animation name with Enums

### ISSUE THREAD

**Issue by PGLongo** [MengTo/Spring#22]
I think it should be better use enum for animation name, curve and properties. If you agree, I could take care about it.

**Comment by schneiderandre** [comment]
Yes, instead of using Strings like ```"fadeIn"``` we could use an enum like this
```swift
enum Animation: String {
    case FadeIn = "FadeIn"
}
```
And since all properties are ```@IBInspectable``` we have to use ```rawValue```.
This gives us the type safety of an Enum in Code and we are still able to set the properties in Interface Builder.

**Comment by jamztang** [comment]
I would like to propose an alternative is to use typealise and constant, to keep the animation in String type value

**Comment by PGLongo** [comment]
In my opinion if String type is not necessary an enum should be used in this case. Instead of search the animation name/constant I could make Animation. and see all the possibility and in Interface Builder  there would be a select box instead of a textfield.

@jamztang explain why you prefer String.

**Comment by jamztang** [comment]
I do prefer enum. Main reason we have to keep it as string type is because IBInpectables does not support drop down for Enums. Unless it already does?

**Comment by PGLongo** [comment]
My mistake. It works only with UIColor.

The only way is with workaround like : 

```swift
enum Animation: String {
    case FadeIn = "FadeIn"
}

@IBDesignable
class SpringView: UIView {

    var animation : Animation = .FadeIn{
        didSet {
            self.animationName = animation.rawValue
        }
    }
    
    @IBInspectable var animationName: String = ""
```

**Comment by schneiderandre** [comment]
@jamztang Using Enums or String Arrays is not possible for IBInspectables.
I would also try to avoid two variables for setting the same property. This leads to confusion.

I would prefer an Enumeration, like I wrote before. In InterfaceBuilder you have to use the String, and in code you can also use the String or the Enumeration:
```swift
springView.animation = SpringView.Animation.FadeIn.rawValue
```

**Comment by PGLongo** [comment]
@schneiderandre Enum doesn't appear in InterfaceBuilder.

**Comment by schneiderandre** [comment]
@PGLongo right, that's what I wrote, but as I mentioned we can use:
```swift
@IBInspectable var animation: String
```
and set it
```swift
springView.animation = SpringView.Animation.FadeIn.rawValue
```

**Comment by jamztang** [comment]
Ok so this is to my surprise that it's not working as well.

```swift
typealias AnimationName = String

class SpringView : UIView {
    @IBInspectable var animation : AnimationName = ""
}
```

I'm actually looking into something like this:
```swift
public struct SpringAnimation {
    static let FadeIn = "fadeIn"
    static let FadeOut = "fadeOut"
    static let SlideLeft = "slideLeft"
}

// So to set it will be slightly nicer
springView.animation = SpringAnimation.FadeIn
```

I do have one for Objective-C but I guess it's way too much addition to the code base, so I'll just link it [here](https://gist.github.com/jamztang/f108b4627f260d79ac8e) for our reference.

**Comment by SachiraChin** [comment]
Swift 1.2 supports @objc enums. 

https://developer.apple.com/swift/blog/?id=22

**Comment by PGLongo** [comment]
@SachiraChin also objc enums doesn't appear in InterfaceBuilder.

**Comment by jamztang** [comment]
Right. I guess right note the best is to just keep our options open, optimistically I think we might see Apple support enums in the future
