### ISSUE TITLE
is unavailable: cannot find Swift declaration for this class

### ISSUE THREAD

**Issue by IcooN** [MengTo/Spring#25]
Hi,

When I building my app in simulator, everything is working, but when I want to build app on device I get errors that different  Spring classes declarations cannot been found, can you help me?

**Comment by jamztang** [comment]
Can you put up some screens of the route you were encountering?

**Comment by IcooN** [comment]
This is top of file, import framework and first use, down below any using of this name are errors the same as in screen 2.
![zrzut ekranu 2015-02-15 o 09 30 16](https://cloud.githubusercontent.com/assets/872037/6202607/7ef9d35a-b4f5-11e4-8f47-a1250c035f85.png)
![zrzut ekranu 2015-02-15 o 09 31 15](https://cloud.githubusercontent.com/assets/872037/6202608/83471314-b4f5-11e4-8077-33b7615f8c1a.png)

and framework class not working here as well.

![zrzut ekranu 2015-02-15 o 09 34 45](https://cloud.githubusercontent.com/assets/872037/6202620/1402e8c4-b4f6-11e4-92e4-431fc4bc4c6a.png)

**Comment by jamztang** [comment]
![image](https://cloud.githubusercontent.com/assets/852375/6202853/53060ff6-b53c-11e4-94b6-06d378ef7e82.jpg)
Try selecting the Spring target and build it once, then back to the SpringApp target and try again.
It usually doesn't need this manual step, it could be some Xcode related issue

**Comment by IcooN** [comment]
I have my own app with copied and imported Spring.framework, in simulator is work perfectly but I have those issues when want build in for phone.

**Comment by jamztang** [comment]
does the SpringApp works on your iPhone?

**Comment by IcooN** [comment]
Yes

**Comment by IcooN** [comment]
Ok, I made it. It's started working when I copied Spring folder and add new target framework to create for my app, importing compiled framework not working.

**Comment by jamztang** [comment]
So there might be some configuration issues on your project. 

What's your iPhone iOS version?
What method did you integrate? (Cocoapods, Carthage, drop in, etc)
Is it an objective c based project or swift?

**Comment by jamztang** [comment]
Ok sounds good that it's start working for you!

**Comment by IcooN** [comment]
Sorry like I written, is needed to great framework for project not importing compiled framework form SpringApp. It's could be my problem ( Designer starting to code :P ). Thank for help, I closing issue.
