### ISSUE TITLE
Update podspec version number

### ISSUE THREAD

**Issue by RishabhTayal** [MengTo/Spring#253]
I am creating a PR to update the pod version number for swift 3. Instead of pointing to `swift3` branch we can have a new pod version for swift 3.

**Comment by RishabhTayal** [comment]
Any update on this one?

**Comment by felipeplets** [comment]
Any update @MengTo? I would like to be able to track sprint by version like I do with other pods.

**Comment by marcosgriselli** [comment]
Podspec updated on 19b04d7
