### ISSUE TITLE
iOS 7 not supported when adding animation in Storyboard 

### ISSUE THREAD

**Issue by imkevinxu** [MengTo/Spring#26]
This is probably intended behavior but there should be a note in the README at least.

I set up an animation for a view in Storyboard and it worked great in iOS 8. When I tested it on iOS 7 the animation defaulted to the slide from right animation. I had to manually add the animation code in a view controller for it to work for iOS 7.

Just a heads up for other people and maybe a note in the README could help!

**Comment by MengTo** [comment]
Thanks for the report. Added that to the README, and looking for a fix!

**Comment by aman340** [comment]
my animation not working properly in storyboard

**Comment by schneiderandre** [comment]
I checked animation support in Storyboards with Xcode 6.4, iOS Simulator 7.1 and Deployment Target 7.1 and everything worked as expected.
It would be great if someone could verify this.

Thanks :+1:
