### ISSUE TITLE
any plan to upgrade support Swift 4?

### ISSUE THREAD

**Issue by jacobjiangwei** [MengTo/Spring#262]
any plan to upgrade support Swift 4?

**Comment by MengTo** [comment]
Yes, I'm sure someone will make a pull request soon. :)

**Comment by jacobjiangwei** [comment]
any update since recent one month? @MengTo

**Comment by MengTo** [comment]
We already have a swift4 branch. :)

**Comment by hemangshah** [comment]
@MengTo, why there's no released for Swift 3.x? At least, there should be some releases for that?

**Comment by fraserscottmorrison** [comment]
@MengTo Why don't you merge the swift 4 branch into master?

**Comment by MengTo** [comment]
@fraserscottmorrison The branch swift4 was merged 5 months ago. Is it not working for you?

**Comment by MengTo** [comment]
I'll close this issue.

**Comment by fraserscottmorrison** [comment]
Ah sorry, Ive been using the swift branch - and from your July comment I didn't think it'd been merged
Thanks!
