### ISSUE TITLE
Revert animations

### ISSUE THREAD

**Issue by jacobmohl** [MengTo/Spring#27]
It would be nice to revert the animation. 

Ex. the slideUp is great for showing content, but when i want to hide it again the only possible animations is right now fall or fadeOut or zoomOut.

I think it would be great if there where a revert property (BOOL), so the animation to "go back".

Correct me if i am wrong.

**Comment by MengTo** [comment]
animateTo is meant to do that. :)

**Comment by MengTo** [comment]
Let me know if managed to achieve the revert animation. I'll close this topic for now. :)

**Comment by rdaneshvar95** [comment]
@MengTo @jacobmohl Any solutions?
