### ISSUE TITLE
Error in Swift 4

### ISSUE THREAD

**Issue by atomicmacon** [MengTo/Spring#277]
I'm getting the following check dependencies error in Swift 4 even though the builds go through:

The use of Swift 3 @objc inference in Swift 4 mode is deprecated. Please address deprecated @objc inference warnings, test your code with “Use of deprecated Swift 3 @objc inference” logging enabled, and then disable inference by changing the "Swift 3 @objc Inference" build setting to "Default" ...

Is there a way to fix these errors so I have a clean build?

**Comment by MengTo** [comment]
Did you use the swift 4 branch? Hasn't been merged yet.

**Comment by atomicmacon** [comment]
Yes, I did. That's the one that is giving the error. It says that @objc is deprecated and it's used throughout the Swift 4 version. Actually I can't tell that anything is different with the Swift 4 version. Has it been updated?

**Comment by atomicmacon** [comment]
I found the issue. During the conversion process, Swift 4 wasn't selected in the build settings. Everything is working find now.
