### ISSUE TITLE
Back Buttons Not Working (From book tutorial)

### ISSUE THREAD

**Issue by jasoncbautista** [MengTo/Spring#29]
Hi =-)

I'm following the "Quick Prototyping in Xcode" chapter of the book and when I first import the Spring Framework, then CTRL + drag from the back button to the exit icon ... I don't seem to get any options to choose like in the video (the single option shown is never seen).

It just cancels out and the back button fails to work?

Any ideas?

I'm using:

Version 6.1.1

I disabled auto layout and tried doing this in a simplified app with only two view controllers but still no luck.

Thanks!

EDIT: Also I downloaded TransitionsDemo and that works fine.. but my own hello world app doesnt. I even copied over the Spring framework fromt here to my app and I still don't get the Presenting Segues unwindToViewController for the Exit component

**Comment by MengTo** [comment]
Did you enable Copy Files if Needed? 

I'd like to take a look at your demo project. Can you zip the folder of your Xcode project and share it on Dropbox via a public link?

**Comment by jasoncbautista** [comment]
Thanks for the quick response.


I did check the copy files if needed.

Heres two examples I started to try to get it to work but neither seem to work:

https://github.com/jasoncbautista/SpringTests


Zip:

https://github.com/jasoncbautista/SpringTests/archive/master.zip



It seems the spring framework is actually copied:

https://github.com/jasoncbautista/SpringTests/tree/master/WorkingS/WorkingS



But when I try to add a custom class of SpringImageView it doens't auto complete either, I assume I must be doing something wrong... but I thought all I had to do is drag and drop (with copy files enabled).

Thanks

**Comment by MengTo** [comment]
Strange, I'm getting this when I try to open your zip file: http://cl.ly/image/0s0y1a081x3w/Archive%20Utility.png

**Comment by jasoncbautista** [comment]
Hey don't worry about it =-)

I don't know whats wrong but it works on my other computer... it's probably some weird obscure Xcode bug (even though its the same version on both computers).

The one working is on 10.10.1
vs the one that doesnt is on 10.10.2

Really strange.....  could be the reason but could be totally unrelated.


In either case, thanks for writing such an awesome book, it's been really great thus far =-)

**Comment by RoopKrrish9696** [comment]
Same here. Imported Succesfully. Shwoing unwind option and all animation presets but neither of them is functional. Could you please see this.
