### ISSUE TITLE
Animation doesn't work when the View Controller is pushed through Navigation Controller.

### ISSUE THREAD

**Issue by rishabhtayal** [MengTo/Spring#31]
I have tested this by creating a test project and applying animation to UIButtons. The root view controller's button animates while the UIButton in next view controller(which is pushed after first button is pressed) does not animate. Both buttons have same SpringButton properties.

I am trying to animating through storyboard.

**Comment by jamztang** [comment]
does it work if you put a long `delay` and `duration`?

**Comment by rishabhtayal** [comment]
I haven't tested that.

**Comment by jamztang** [comment]
Just confirmed the issue. `AutoStart` It works for Model presentation and Push (no animation) presentation. But the normal Push transition somehow overrides the animation block.
![ios simulator screen shot 10 mar 2015 1 22 18 pm](https://cloud.githubusercontent.com/assets/852375/6569615/7d83eb24-c728-11e4-9a7a-5bd103d46898.png)

I spend some time debugging but unfortunately don't have an immediate solution now.
The best possible workaround so far I have discovered is to animate your target view on `viewDidLoad()` manually.

**Comment by Neejoh** [comment]
Is that because the segue goes through the navigation controller instead of directly to a different view? I'm no Swift guru (just wrote my first lines of code this morning), but I've followed the Stanford Swift course and the instructor talks about this. See [Youtube: 52:20 ~ 55:10](https://youtu.be/gjl2gc70YHM?t=52m21s)

I might be completely wrong here, but it might be useful?

**Comment by connman21** [comment]
Has anyone ever resolved this? I'd love to know if there is a workaround that still keeps the animation in the Storyboard. This animation framework is awesome... I'd love to use it in the app I'm about to release.

**Comment by connman21** [comment]
jamztang -- How would I get this to autostart in code?

**Comment by jamztang** [comment]
Try this in viewDidLoad

someView.animate()

**Comment by schneiderandre** [comment]
I came up with a solution that you can see in #88. All segue transitions seems to work fine now.

![screen recording 2015-07-20 at 07 25 nachm](https://cloud.githubusercontent.com/assets/975938/8782495/15488eba-2f16-11e5-868c-6f24342aa279.gif)

If anyone wants to test this feature branch before merging, that would be great! :+1:

**Comment by connman21** [comment]
Thanks Andre... excited to take a look this afternoon! 

Jeremy Conn
connman21@gmail.com

**Comment by schneiderandre** [comment]
@connman21 great, thanks :+1:

**Comment by connman21** [comment]
@schneiderandre I'm a GitHub newbie -- how do I download your code changes?

**Comment by schneiderandre** [comment]
@connman21 just click on the branch tab and select the `feature/navigation-controller-animation` branch. Then you can download the zip file.

<img width="478" alt="bildschirmfoto 2015-07-20 um 23 46 58" src="https://cloud.githubusercontent.com/assets/975938/8788296/abc3c648-2f39-11e5-8221-0e720f45c67a.png">

**Comment by connman21** [comment]
@schneiderandre It works amazingly! Nice work!

**Comment by schneiderandre** [comment]
Thanks! Looks like this is fixed now, but let us know if you’re still experiencing this problem :+1:.

**Comment by rishabhtayal** [comment]
@jamztang Someone still having this issue? I am.

**Comment by jamztang** [comment]
Would you provide some sample code so that people can trace around here?

**Comment by rishabhtayal** [comment]
@jamztang Here is a sample project in swift which shows the issue in Spring animation. Please feel free to play around with the project. https://github.com/rishabhtayal/SpringExample

**Comment by schneiderandre** [comment]
@rishabhtayal thanks for your example project. Spring should work, but the Podspec is not updated yet. Since you are using CocoaPods, you aren't using the newest version. I changed your Podfile to
```ruby
platform :ios, "8.0"
use_frameworks!
pod "Spring", :head
```
to include the newest Spring commits and everything worked as expected. Please give it a try!

**Comment by rishabhtayal** [comment]
That works...!!! :thumbsup:

**Comment by Osama92** [comment]
Just implemented viewDidLayoutSubview() method, put the animation within the method and it works fine. Thank you!
