### ISSUE TITLE
Spin Animation & Animation Loop

### ISSUE THREAD

**Issue by yelled3** [MengTo/Spring#32]
Hello,
Let me just start and say I'm a really hyped about Spring :-)

I was wondering if there's a way to animate a spinner through storyboard properties. e.g make an image rotate a in a loop.

I did found this in the code:
https://github.com/MengTo/Spring/blob/master/Spring/LoadingView.swift#L30-L36

but I think this kind of simple animation would be easier to customize from a storyboard.

also, in the source code I saw that looping the animation was done via `animation.repeatCount = HUGE` 
shouldn't there just be a flag for `animation.repeatsForever = true`
which you can toggle from the storyboard

@MengTo WDYT?

**Comment by MengTo** [comment]
I think it may be simpler to just put repeatCount to 9999 instead of adding an extra field for repeatsForever. That may be a little redundant? :)

The loadingView was meant to be used as a function called before and after data loads. Those events typically happens only in code.

**Comment by MengTo** [comment]
Let me know if that's okay. I'm closing the topic for now.
