### ISSUE TITLE
Zoom Transition messing up CollectionView Flow Layout Causing Jerk on Return

### ISSUE THREAD

**Issue by agibson73** [MengTo/Spring#39]
The title says it all but because the transform is applied, the collectionview tries to constantly update the flow layout so it jerks when you return to that view.  I have written a fix but being a Github Newbie I don't know what to do with it. Advise and I will share.  You can review and decide if it is better or should be an additional transition.  I also have a couple of other transitions that I would be willing to add.

Thanks,
Alex

**Comment by MengTo** [comment]
I just gave it a test and it didn't seem to jerk for me. Can you show me a video of what you mean?

**Comment by agibson73** [comment]
Meng,
I have sent it to you in a messenger message.  Github does not support
videos.

Alex

**Comment by agibson73** [comment]
![demogif](https://cloud.githubusercontent.com/assets/8474760/6657874/bd710622-cb2e-11e4-9e1f-2db8ae799ddc.gif)

**Comment by agibson73** [comment]
With my changes it looks like this
![gifmw](https://cloud.githubusercontent.com/assets/8474760/6659002/a5065002-cb50-11e4-8a0e-daf8d3dca78a.gif)

**Comment by schneiderandre** [comment]
Looks good to me now! :+1:
