### ISSUE TITLE
'selectedImageTintColor' was deprecated in iOS 8.0: Use tintColor

### ISSUE THREAD

**Issue by leny** [MengTo/Spring#41]
Hi,

In the new XCode 6.3 beta (6D543q), I got the following warning : 

> /…/Spring/DesignableTabBarController.swift:22:35: 'selectedImageTintColor' was deprecated in iOS version 8.0: Use tintColor

I don't have the last version of the file, but the [line still exists](https://github.com/MengTo/Spring/blob/master/Spring/DesignableTabBarController.swift#L36) in the last version.

I don't use this class in my app, so I will change the value locally, but I don't know if it can be changed for people who use the class. :)

**Comment by MengTo** [comment]
Thanks for the feedback. We'll make sure to make the change when we support 6.3 soon. :)

**Comment by leny** [comment]
Glad I could help. :wink:

**Comment by MengTo** [comment]
Fix applied. Thanks!
