### ISSUE TITLE
Back button does not nothing

### ISSUE THREAD

**Issue by alvagorn** [MengTo/Spring#42]
I'm starting the Tutorial from your book but I've imported the Spring framework to the project and when I've set the  segue to "unwindToViewController" and Run the project, the Back button does nothing....Please help me ;) Regards,

Álvaro.

**Comment by MengTo** [comment]
There is a known issue where if you're using Over Current Context in a Table VC, it won't work. Let me know if that's the case for you.

**Comment by alvagorn** [comment]
Sorry, i don't understand what's Over Current Context. I've just started the Tutorial Section "Quick prototyping in Xcode" and followed step-by-step... Thanks in advance for your quick reply ;)

**Comment by alvagorn** [comment]
I'm using Xcode  6.2 and OSX 10.10.2.

**Comment by MengTo** [comment]
Can you zip your Xcode project folder and share it? 

Also, if you have troubles, please download the Xcode projects from the tutorials.

**Comment by alvagorn** [comment]
Ok, I'll try comparing both folders and if I don't discover the issue I'll send you the zipped folder. Thanks a lot;)

**Comment by MengTo** [comment]
Awesome, keep me updated.

**Comment by alvagorn** [comment]
Sorry Meng To, I've just re-started the IOS Simulator and it just Works Great! Thank You Very Much for your attention and sorry....;)

**Comment by MengTo** [comment]
Ah wonderful to hear! Yeah Xcode sometimes just need a little restart. :)
