### ISSUE TITLE
How to get the animate end event?

### ISSUE THREAD

**Issue by skytodmoon** [MengTo/Spring#43]

**Comment by skytodmoon** [comment]
I use this "func springWithCompletion(duration: NSTimeInterval, animations: (() -> Void)!, completion: ((Bool) -> Void)!)" but the completion have no time delay effect, is anybody know this?

**Comment by MengTo** [comment]
If you're going to use Delay, I'd just use the UIView.animateWithDuration functions.

UIView.animateWithDuration(0.5, delay: 0.1, options: nil, animations: {
    
    // Animate something
    
}, completion: nil)

**Comment by skytodmoon** [comment]
sorry, I have not described clearly. I want to "remove the view or sth" after the animate over, just like below code:

UIView.animateWithDuration(1.0, someAnimate, removeView)

    func removeView(finished:Bool){
        if finished{
         self.view .removeFromSuperview()
        }

    }

But I find the completion is invalid, it occur just after I invoke the "UIView.animateWithDuration(1.0, someAnimate, removeView)". have no completion effect.

**Comment by MengTo** [comment]
Then use the completion method. 
Or use Spring's 
    animateToNext {  
        // remove 
    }
