### ISSUE TITLE
LoadingView.xib missing?

### ISSUE THREAD

**Issue by frizzy75** [MengTo/Spring#44]
I'm using CocoaPods to integrate Spring, but the app crashes when calling view.showLoading( ):
"Could not load NIB in bundle...with name 'LoadingView'"

Could this be because LoadingView.xib is not included in the podspec? I'm new to CocoaPods, but the podspec has: "s.source_files = 'Spring/*.swift' " -- should there also be: ",*.xib" ?

Thanks

**Comment by jamztang** [comment]
Yes you're right, we're working on a fix, in the mean time you can copy **LoadingView.xib** and **loading.pdf** from **Image.xcassets** into your project.

**Comment by jamztang** [comment]
Oh looks like it wouldn't work until the resource files are actually inside the library, please stay tuned.

**Comment by frizzy75** [comment]
Thanks @jamztang - I will wait for the fix. And thanks for Spring!

**Comment by jamztang** [comment]
Please try again :D

**Comment by frizzy75** [comment]
Working! Thank you very much @jamztang !

**Comment by jamztang** [comment]
you are welcome :)
