### ISSUE TITLE
error: 'AsyncImageView' is ambiguous for type lookup in this context

### ISSUE THREAD

**Issue by fidergo-stephane-gourichon** [MengTo/Spring#49]
When using [AsyncImageView 1.5.1](https://github.com/nicklockwood/AsyncImageView/) and [Spring](https://github.com/MengTo/Spring), both as pods in a Swift project, the following compile-time error occurs:

<pre>
error: 'AsyncImageView' is ambiguous for type lookup in this context
    @IBOutlet weak var myvariable:AsyncImageView!
                                  ^~~~~~~~~~~~~~
AsyncImageView.AsyncImageView:1:29: note: found this candidate
@objc(AsyncImageView) class AsyncImageView : UIImageView
                            ^
Spring.AsyncImageView:1:13: note: found this candidate
@objc class AsyncImageView : UIImageView
</pre>

The traditional tool to fix such problems is separate namespaces, but there are no namespaces.

Based on similar problem https://github.com/Haneke/HanekeSwift/issues/147 and instructions in https://github.com/raywenderlich/swift-style-guide#class-prefixes or http://stackoverflow.com/questions/24214863/swift-class-prefix-needed, I tried to prefix the type specification like this:

    @IBOutlet weak var myvariable:AsyncImageView.AsyncImageView!

but it produced the exact same error message.

How to use both pods in a project ?

**Comment by schneiderandre** [comment]
I tried to reproduce this error with the following configuration without any issues:

- Xcode 6.4 / SDK 8.4
- Swift Project
- CocoaPods 0.37.2
- Podfile:
```
use_frameworks!
pod 'Spring', '~> 1.0'
pod 'AsyncImageView', '1.5.1'
```
Were you able to fix the error in the meantime?

**Comment by fidergo-stephane-gourichon** [comment]
Thank you for your test and reply. Our investigations were misguided by some prior problems with pods in multi-target environment. We noticed that some other dependency brought another incompatible class named AsyncImageView in the same scope. That seems to be the actual cause. Problem solved. Thanks.

**Comment by schneiderandre** [comment]
My pleasure. Glad it's working now! :+1:
