### ISSUE TITLE
Open Cocoapods to ios 7.x ?

### ISSUE THREAD

**Issue by allaire** [MengTo/Spring#50]
Cocoapods is pinned to 8.x. Anyway to open it up to support iOS 7x?

**Comment by schneiderandre** [comment]
Hey @allaire, sorry for the late response.

**Comment by schneiderandre** [comment]
Hey @allaire, sorry for the late response.

The minimum deployment target with Swift in CocoaPods is iOS 8.0. All Pods in Swift are build as dynamic frameworks, which only work on iOS 8+.
If you want to use Swift projects with iOS 7.x you have to copy the files manually.
(see https://github.com/CocoaPods/swift/issues/22)
