### ISSUE TITLE
AddSubView to SpringView

### ISSUE THREAD

**Issue by gautierdelorme** [MengTo/Spring#52]
Hi everyone !
Why is it not possible to add a subview in a SpringView ?
addSubView(myView) does not work...

I have a custom subclass ChooseButton of SpringView and I want to add a subview (mySubView in this case) to this view :

```swift
class ChooseButton: SpringView {
     enum TypeButton {
        case YES, NO
    }

    var type:TypeButton!
    var size:CGFloat = 90

    var enabled: Bool!
    var delegateButton: ChooseButtonDelegate?

    init (type: TypeButton) {
        super.init(frame: CGRectMake(0,0,size,size))
        self.type = type
        enabledButton()
        if type == TypeButton.YES {
            self.backgroundColor = CustomColor.Emeralde
            self.center = CGPointMake(gScreenSize.width*3/4, gScreenSize.height-self.frame.size.height)
        } else {
            self.backgroundColor = CustomColor.Alizarin
            self.center = CGPointMake(gScreenSize.width/4, gScreenSize.height-self.frame.size.height)
        }
        self.layer.cornerRadius = size/2

        var mySubView = UIView(frame: frame)
        mySubView.backgroundColor = UIColor.blackColor()
        addSubview(mySubView)
    }
```
But my Subview does not shows up... I can't see why.

**Comment by jamztang** [comment]
While I don't have your other files
I copied your code to a new file and make a few changes to make it compilable **ChooseButton.swift**

```swift
protocol ChooseButtonDelegate {

}

class ChooseButton: SpringView {
    enum TypeButton {
        case YES, NO
    }

    var type:TypeButton!
    var size:CGFloat = 90

    var enabled: Bool!
    var delegateButton: ChooseButtonDelegate?

    init (type: TypeButton) {
        super.init(frame: CGRectMake(0,0,size,size))
        self.type = type
//        enabledButton()
//        if type == TypeButton.YES {
//            self.backgroundColor = CustomColor.Emeralde
//            self.center = CGPointMake(gScreenSize.width*3/4, gScreenSize.height-self.frame.size.height)
//        } else {
//            self.backgroundColor = CustomColor.Alizarin
//            self.center = CGPointMake(gScreenSize.width/4, gScreenSize.height-self.frame.size.height)
//        }
        self.layer.cornerRadius = size/2

        var mySubView = UIView(frame: frame)
        mySubView.backgroundColor = UIColor.blackColor()
        addSubview(mySubView)
    }


    required init(coder aDecoder: NSCoder) {
        fatalError("init(coder:) has not been implemented")
    }

}
```

In **SpringViewController.swift**
```swift
override func viewDidLoad() {
    super.viewDidLoad()
    
    animationPicker.delegate = self
    animationPicker.dataSource = self
    animationPicker.showsSelectionIndicator = true

    let button = ChooseButton(type: .YES)
    button.backgroundColor = UIColor.yellowColor()
    self.view.addSubview(button)
}
```

And I get this
![ios simulator screen shot 10 apr 2015 7 33 56 pm](https://cloud.githubusercontent.com/assets/852375/7086887/8b85a980-dfb8-11e4-940c-8fd85c2b5868.png)

I assume your subclass works, just there're some views covering up. And you can also use **Debug View Hierarchy** to check.

![screen shot 2015-04-10 at 7 35 28 pm](https://cloud.githubusercontent.com/assets/852375/7086936/d61c584a-dfb8-11e4-930f-d5f662163047.png)
Hope it helps :)

**Comment by jamztang** [comment]
okay now I see that you're changing your `self.center` into something else.
Updating the `center` property actually updates the `frame`, if you print it out you should see something like {142.5, 288.5, 90, 90}.

Then you're adding your subview using the same `frame` value, while it's relative to it's parent, it'll be way off the bounds.

So instead of initializing your view with `UIView(frame: frame)`, you can use `UIView(frame: CGRectMake(0, 0, 90, 90))`

**Comment by gautierdelorme** [comment]
It's working ! Thanks a lot :)
