### ISSUE TITLE
check the animation is complete

### ISSUE THREAD

**Issue by MilaFabio** [MengTo/Spring#54]
This method does not wait for the animation is complete.
Removing immediately, and no animation.
Is it possible to determine when the animation is completed in full?
How to fix?

<pre><code>layer.animation = "pop" 
layer.duration = 1.0
layer.animateToNext {  
    removeView()
} </code></pre>
At the moment I can only do this through dispatch_after.

**Comment by MengTo** [comment]
Just committed the fix. Let me know that works for you. For now I'm closing the issue. :)
