### ISSUE TITLE
ZoomIn effect show "Cover Vertical" Instead.

### ISSUE THREAD

**Issue by ajthechan** [MengTo/Spring#55]
Prototyping Animations Without Code
https://designcode.io/swiftapp-spring

I did something wrong and I couldn't found what I missed. After implementing The "zoomIn" effect in the simulator show "Cover Vertical" instead. Thanks in advance.

**Comment by MengTo** [comment]
The zoomIn only works on objects like UIView, UIButton, etc. Cover Vertical is a segue transition and cannot be used with the Spring animation zoomIn.

**Comment by ajthechan** [comment]
Good point.
Fixed: Animation attributes was set zero.

Thank you! Love you work.

**Comment by MengTo** [comment]
Thanks! Glad you were able to fix it. :)
