### ISSUE TITLE
Warnings on Storyboard since Xcode 6.3

### ISSUE THREAD

**Issue by benji031** [MengTo/Spring#59]
Since Xcode update (6.3), I have warnings that appears on storyboard : 

```
Main.storyboard: warning: IB Designables: Ignoring user defined runtime attribute for key path "animation" on instance of "UIView". Hit an exception when attempting to set its value: [<UIView 0x7fcc64aa4630> setValue:forUndefinedKey:]: this class is not key value coding-compliant for the key animation.
```

I have the same warning for "autostart" and "cornerRadius". But when I build, that still working.

**Comment by MilaFabio** [comment]
there is a solution  <link>http://stackoverflow.com/questions/26674111/ib-designable-ibinspectable-interface-builder-does-not-update</link>
