### ISSUE TITLE
Installation problem

### ISSUE THREAD

**Issue by digitaldesaster** [MengTo/Spring#60]
Hi, i downloaded the sample project and it works as expected. I have started a new swift project in xcode (6.3) and copied the "Spring" folder to my files.

In my storyboard i put in a simple UIView and i can set the class to "SpringView". In the inspector i see the new Spring fields, i set Autostart to on and put in the value "shake" for Animation. If i start my project the UIView stays where it is. it does not work.

if i put a new UIView to your sample-project and set the Class to SpringView. The module is automatically filled with "Spring". This does not happen on my new projected. 

So i think i am missing something.

thanks for help.
dd

**Comment by digitaldesaster** [comment]
while adding the folder, the option "create folder references" was selected. but it only works if you select "create groups". 

http://imgur.com/94cWRuZ

**Comment by MengTo** [comment]
Glad you found the solution. I'll close this issue. :)
