### ISSUE TITLE
How to define the background color with DesignableButton?

### ISSUE THREAD

**Issue by neohang** [MengTo/Spring#63]
There is no any background color option in Attributes inspector panel, only Border, Shadow,Text Color and Background Image. And I download your Xcode project, there is only cornerRadius in Runtime Attributes, but your button is right in BLUE although you don't have any blue color defined in Attributes inspector panel.
How to define the background color with DesignableButton?

**Comment by MengTo** [comment]
The background color can be customized natively without the Spring framework.
![screen shot 2015-04-12 at 10 29 47 pm](https://cloud.githubusercontent.com/assets/1065452/7105753/7b157e66-e163-11e4-9732-2080edcc5394.png)
