### ISSUE TITLE
KeyboardLayoutConstraint.swift using programmatically?

### ISSUE THREAD

**Issue by rsdrsd** [MengTo/Spring#68]
When working with the storyboard and the KeyboardLayoutConstraint.swift file, the keyboard is working great and the view attached to the bottom goes up. However I want to do everything pure programmatically.

I have something like below:
```
let views = ["messagesTableView": messagesTableView,"addMessageView": addMessageView,"addMessageTextField": addMessageTextField]

let keyboardViewV = KeyboardLayoutConstraint(item: addMessageView, attribute: NSLayoutAttribute.Bottom, relatedBy: NSLayoutRelation.Equal, toItem: self.bottomLayoutGuide, attribute: NSLayoutAttribute.Bottom, multiplier: 1.0, constant: 0.0)
self.view.addConstraint(keyboardViewV)

let messagesViewV = NSLayoutConstraint.constraintsWithVisualFormat("V:|[messagesTableView][addMessageView]", options: NSLayoutFormatOptions(0), metrics: nil, views: views)
self.view.addConstraints(messagesViewV)
```
I've added all the constraints, but when I run my app, the keyboard goes up, but the addMessageView which is attached to the bottom layout guide, doesn't go up. The awakeFromNib function should fire, but nothing happens. What is going wrong? Is it even possible to do something like this programmatically? I tried a lot, but nothing works. I even changed the KeyboardLayoutConstraint.swift file to look for a better function than awakeFromNib, but this also doesn't work.

**Comment by rsdrsd** [comment]
Well, finally I've found how to use this class programmatically.

Just replace awakeFromNib() with init() and you've to multiply the return value of updateConstant with minus 1. I guess this is due to the fact that the following code is reversed.

```
let keyboardViewV = KeyboardLayoutConstraint(item: addMessageView, attribute: NSLayoutAttribute.Bottom, relatedBy: NSLayoutRelation.Equal, toItem: self.bottomLayoutGuide, attribute: NSLayoutAttribute.Bottom, multiplier: 1.0, constant: 0.0)
self.view.addConstraint(keyboardViewV)
```

**Comment by jamztang** [comment]
Thanks for that. Would you like to provide a pull request on this? We'll just need to make sure both Storyboard/Code will do the job.

**Comment by rsdrsd** [comment]
Well, it's just handy for people who want to use the file without a story board. So I don't think a pull request is ok. It doesn't add extra value to your great framework.

**Comment by schneiderandre** [comment]
@rsdrsd thanks for sharing your solution!
Since no pull request is needed, I close the issue for now! :+1:
