### ISSUE TITLE
Force animation stop 

### ISSUE THREAD

**Issue by yuchuqiao** [MengTo/Spring#69]
HI, 
Spring is amazing lib, I do like it. When I set a 9999 repeat count for the animation. How I can stop it ? I search the code and issues, did not find the solution yet. Any solution about this?

Thanks!

**Comment by alkait** [comment]
You can run a timer that repeats forever to run 1 animation at a time.  When you decide to stop it at any moment just invalidate the timer.

**Comment by schneiderandre** [comment]
You can call `yourView.layer.removeAllAnimations()` in code to remove all attached animations.

Hope this helps :+1:. I'll close this issue for now.

**Comment by yuchuqiao** [comment]
@schneiderandre That helps thanks a lot!

**Comment by schneiderandre** [comment]
@yuchuqiao Great! :+1:
