### ISSUE TITLE
Unwind to ViewController

### ISSUE THREAD

**Issue by Neejoh** [MengTo/Spring#70]
I can't get the unwind to viewcontroller working. I followed the exact steps shown in the  "Quick Prototyping in Xcode" chapter on DesignCode.io

Thing is, in my version of Xcode (Version 6.3.2 (6D2105)) it says "modal" segue is deprecated. "present modally" is available, but it does not play nice when I try to get a back button working.

Or am I doing something wrong?

Simple scene with two view controllers;
View 1: A button that is ctrl-dragged to View 2: Present modally
View 2: A button that is ctrl-dragged to the exit of View 2: Unwind to Viewcontroller

[» Animated GIF with my example](https://cloud.githubusercontent.com/assets/7911547/7881580/cab9a77e-0604-11e5-84f8-df88de78d0c7.gif)

**Comment by MengTo** [comment]
Please make sure to select create groups when importing.




Thanks! Meng

**Comment by Neejoh** [comment]
Wow, I completely missed that. That did its magic, thanks Meng!
