### ISSUE TITLE
update to Swift 2.0

### ISSUE THREAD

**Issue by krishaamer** [MengTo/Spring#71]
Hi, I'm getting errors in Xcode 7. Do you have plans to update to Swift 2.0?

Thanks,
Kris

**Comment by MengTo** [comment]
Yep: https://github.com/MengTo/Spring/tree/swift2 :)

**Comment by shuenw** [comment]
Thank you for the hard work. I downloaded the zip file for swift2, then dragged the Spring folder in but I keep getting an error that the compile fails. Using Xcode7 as well. Any tips?

**Comment by giannigdev** [comment]
Hi, i am still getting errors with Xcode (Version 7.0 beta (7A120f) ), should i convert the code to  Swift 2.0 as is prompted here:

![screen shot 2015-06-30 at 00 53 45](https://cloud.githubusercontent.com/assets/4886490/8420422/84aa4a64-1ec2-11e5-89fe-8e97399ddd0f.png)

**Comment by MengTo** [comment]
I just updated all the files to Beta 2. Give it a try.






Thanks! Meng

**Comment by schneiderandre** [comment]
I removed the warnings for beta 3.

**Comment by giannigdev** [comment]
Tried now and there are still errors. I am currently reading Swift 2 books and noticed that some Xcode suggestions(for fixing the errors) are right and others have no sense at all. I will hope one day to be able to run this library on my iphone;  I made a screenshots:

![foto](https://cloud.githubusercontent.com/assets/4886490/8826758/0a187d24-3089-11e5-9e8f-494031192e3c.png)

**Comment by schneiderandre** [comment]
@giannigdev are you using the swift2 branch?

**Comment by giannigdev** [comment]
you are right, i forget that, now the build succeeded, thanks !

**Comment by schneiderandre** [comment]
Perfect :+1:
