### ISSUE TITLE
Is there anybody know how to call "springWithComlpetion" in Object-C code?

### ISSUE THREAD

**Issue by lmcmz** [MengTo/Spring#72]
I'm so confuse about using Spring framework in OC.
I already have read the another example which made by author about using Spring in OC.
But the example code is no enough for me to understand.
I'm the freshman on the way of changing Swift to OC.
I hope anyone can answer my question.
Thank you!

**Comment by schneiderandre** [comment]
You can't call this function when using Objective-C.
`springWithCompletion(duration: NSTimeInterval, animations: (() -> Void)!, completion: ((Bool) -> Void)!)`is implemented as a top-level function, which are not available in Objective-c.

This is from [Apple's Mix and Match documentation](https://developer.apple.com/library/ios/documentation/Swift/Conceptual/BuildingCocoaApps/MixandMatch.html): 
>You’ll have access to anything within a class or protocol that’s marked with the [at]objc attribute as long as it’s compatible with Objective-C. This excludes Swift-only features such as those listed here:
>
>Generics
>Tuples
>Enumerations defined in Swift
>Structures defined in Swift
>Top-level functions defined in Swift
>Global variables defined in Swift
>Typealiases defined in Swift
>Swift-style variadics
>Nested types
>Curried functions
