### ISSUE TITLE
How to set the image with rounded corner by `DesignableButton` with `cornerRadius`?

### ISSUE THREAD

**Issue by chenweiyj** [MengTo/Spring#73]
I have a `DesignableButton` of size 80x80 with `cornerRadius` of 40, aiming to change the avatar image when clicked. However, when I invoke `setImage` with normal control state, the avatar image is all shown in the button with any rounded corner. I have also tried to set `cornerRadius` to 40 after `setImage`, but it still fails. So I wonder how to do it. Thank you.

**Comment by lastMove** [comment]
try to set clipstobounds to true of your DesignableButton

**Comment by MengTo** [comment]
Yes, the Clip Subviews option for UIImage should solve this.
