### ISSUE TITLE
Swift Cocoapod Issue

### ISSUE THREAD

**Issue by keyclipse** [MengTo/Spring#76]
I am trying to compile my project with Spring as its cocoapod dependency.

I am using xcode 6.4 and I keep getting this segmentation fault 11 error.

1.	While type-checking 'viewDidLoad' at /Users/samuelkitono/Airward/airward-client-swift/AirwardLoadingViewController.swift:18:14
2.	While type-checking expression at [/Users/samuelkitono/Airward/airward-client-swift/AirwardLoadingViewController.swift:20:9 - line:20:142] RangeText="self.checkmarkSpringImageView.image = self.checkmarkSpringImageView.image?.imageWithRenderingMode(UIImageRenderingMode.AlwaysTemplate)"
3.	While deserializing 'init' (ConstructorDecl #330) 
4.	While deserializing decl #573 (XREF)
5.	Cross-reference to module 'UIKit'
	... UIImageView

Tried cleaning the project and rebuild.
Tried quitting xcode and rebuild
None of them work...

**Comment by schneiderandre** [comment]
I tried to reproduce you issue and was using `Xcode Version 6.4 (6E35b)` and `Swift` with the following podifile:
```
use_frameworks!
pod 'Spring', '~> 1.0'
```
without any issues.
Maybe you can provide some additional information so that we can solve your issue.

Thanks :+1:

**Comment by schneiderandre** [comment]
Hey @keyclipse, since there was no feedback over the last Month, I assume that everything works now and the issue can be closed.
Let us know if you’re still experiencing this problem. :smile:
