### ISSUE TITLE
CGBlendMode.Type' does not have a member named 'Normal'

### ISSUE THREAD

**Issue by idriskhenchil** [MengTo/Spring#77]
I'm currently running Swift 2, with Xcode 7 and using the `swift2` branch of Spring. Upon building the project I am given this error

    /Desktop/Swift/Dynamic/Pods/Spring/Spring/DesignableTabBarController.swift:110:40: 'CGBlendMode.Type' does not have a member named 'Normal'

Any ideas? I've already tried building and cleaning.

**Comment by MengTo** [comment]
The update has been made for beta 2, please make sure to update your Xcode.




Thanks! Meng

**Comment by idriskhenchil** [comment]
Just upgraded, still having the same issue. Trying installing via CocoaPods `0.37.0` and `0.38.0.beta.1`

**Comment by MengTo** [comment]
Oh I'm not sure about cocoapods installation. 




Thanks! Meng

**Comment by idriskhenchil** [comment]
My bad, I installed Xcode twice, and as you know it'll add a `2`, so I thought it was updated. Solved so many problems I've had. Just one more question, does Spring not work on `UIView`?  I get errors when I try to pull that off
![screen shot 2015-07-03 at 9 49 26 pm](https://cloud.githubusercontent.com/assets/5817836/8506033/67f83422-21cd-11e5-9a96-3baec9b25956.png)

**Comment by MengTo** [comment]
It should work. Probably spring wasn't properly installed. Did you enabled create groups?




Thanks! Meng

**Comment by idriskhenchil** [comment]
That's correct, I did enable it.

**Comment by MengTo** [comment]
Oh yeah, if you’re using Cocoapods, you have to do import Spring



Thanks! Meng

**Comment by idriskhenchil** [comment]
Already imported beforehand, still wasn't working. Since I needed a radius on the view, I just added it via storyboard then applied the animation through there, then created and outlet in the ViewController and added the radius there. So I guess I got it working :)

**Comment by redlamp** [comment]
Hey Meng,

I've been going through the Design+Code tutorials this past week and have run into this problem when both manual importing Spring into the project (following the tutorial) and again when trying to use Cocoapods (which I'm new to, so I might have done something wrong).

As a temporary solution I commented out the line, but that seems like a dangerous path to head down.

I'm using Xcode-Beta, Version 7.0 beta (7A120f).

**Comment by idriskhenchil** [comment]
Update to the latest beta. I'm not sure if `7A120f` is the second (I feel like it's the first). That should fix the issue for you @redlamp

**Comment by redlamp** [comment]
@idriskhenchil That was it, I grabbed the wrong installer DMG from desktop to laptop.
