### ISSUE TITLE
Reverse animation for exit transitions?

### ISSUE THREAD

**Issue by alkait** [MengTo/Spring#78]
Is there a way to do any of the available animation in reverse? Say you want to "slideOutLeft" to do an exit animation.  How to achieve this?

**Comment by MengTo** [comment]
Yes, you have to use code for that. So use animateTo() instead of animate().



Thanks! Meng

**Comment by paultan1080** [comment]
Hi,
Could you please explain when we have to use animateTo(). I want to show hide a SpringView. Show with a animation, hide with same animation but reverse, please help.

**Comment by MengTo** [comment]
Sure, here’s the code:

layer.animation = “slideLeft”

layer.animateTo()




—

animate() would slide right to left.

animateTo() would slide left to right.



Thanks! Meng

**Comment by paultan1080** [comment]
Ah Thanks, works like charm!
