### ISSUE TITLE
unwind segue to viewcontroller not working

### ISSUE THREAD

**Issue by yaronbbb** [MengTo/Spring#79]
xcode 6.4
os 10.10.4
latest spring library
ios sdk 8.4

no errors , just the back button does nothing , any ideas ?

**Comment by schneiderandre** [comment]
I tried to reproduce your issue with
- Xcode Version 6.4 (6E35b)
- Swift
- Spring 1.0.3
- iOS SDK 8.4
- OS X 10.10.4

here it works. Did you connect your button to the exit segue?
![bildschirmfoto 2015-07-06 um 17 33 52](https://cloud.githubusercontent.com/assets/975938/8526171/4b404eac-2405-11e5-912a-6535017bd077.png)

**Comment by yaronbbb** [comment]
1.i dropped the spring folder into the project
2. set 2 views
3. set 1 button to point at 2nd page
4. set new button and dragged (ctrl) into exit and choose unwind..
action->unWindToviewController

how can i check that spring is actually imported fine ?

**Comment by yaronbbb** [comment]
presenting segues
unwindTo... -> action button

**Comment by schneiderandre** [comment]
If you can see the `unwindToViewController` action, Spring should be imported correctly.
Can you see the `Unwind segue to Scene Exit Placeholder` in the Document Outline?

![bildschirmfoto 2015-07-06 um 19 05 40](https://cloud.githubusercontent.com/assets/975938/8528232/1acf105c-2412-11e5-942b-540e82cc59e9.png)

**Comment by yaronbbb** [comment]
yes, exactly that

**Comment by schneiderandre** [comment]
That's strange, I assume your project isn't open source?
If you're interested, I can put the sample project on Github, so you can check it there.

**Comment by yaronbbb** [comment]
the sample project works fine , it is just when adding spring to new project and doing the screens link / back  it does not.

**Comment by yaronbbb** [comment]
it was such a stupid thing, when you drag and drop the 'Spring' folder into the project you must check under "added folders" -> "create groups" and not "create folder reference"

**Comment by jacobmohl** [comment]
I have this issue when I use CocoaPods. I supose that the "create group" is not an option? 

But I have not that much experience with CocoaPods.

**Comment by schneiderandre** [comment]
@jacobmohl hey, thanks for your report. I tested it with CocoaPods and didn't encounter any issues. It would be great if you can provide some additional information to reproduce this :smile:

**Comment by jacobmohl** [comment]
I have a segue with "Present modally" and "Over current context" with a "Cross dissolve" transition. 
<img width="1552" alt="skaermbillede 2015-07-22 kl 21 55 36" src="https://cloud.githubusercontent.com/assets/3217561/8835745/9fd7cf30-30bc-11e5-88ee-50279e056428.png">

In the  ViewController which are presented modally I have a big button covering the whole background with an action to unwindToViewController.
<img width="1552" alt="skaermbillede 2015-07-22 kl 21 55 10" src="https://cloud.githubusercontent.com/assets/3217561/8835758/b972f244-30bc-11e5-93e4-4d5cb8581fc9.png">

Much like the login view controller in the DN app from Design+Code.

**Comment by jacobmohl** [comment]
It works if i used the deprecated Modal segue. Should i raise a new issue for this, as it is a iOS 8 and forward problem.

**Comment by schneiderandre** [comment]
@jacobmohl sounds like a good idea! Thanks for creating a new issue! :smile:

**Comment by danharsanyi** [comment]
@yaronbbb I had exactly the same issue, doesn't make any sense. Your fix (Checking create groups) worked for me as well. Thanks mate
