### ISSUE TITLE
Licencing Issues

### ISSUE THREAD

**Issue by remaerd** [MengTo/Spring#8]
Hello Meng, Thanks for your contribution.
Although there's a couple licensing issues of your new framework which may get you into troubles.

You may consider remove Proxima Pro from your library. It's a commercial software and it cannot redistribute like this. If you really care about fonts, You may consider changing to an open license font.

You may need to add a LICENCE file to your open source framework, also.

Thats all. Wish you all the best.

**Comment by MengTo** [comment]
Ah you're right, will fix this asap!

**Comment by MengTo** [comment]
Font removed. Will update the license shortly!
