### ISSUE TITLE
use of undeclared type "SpringImageView"

### ISSUE THREAD

**Issue by oshiltawi** [MengTo/Spring#80]
use of undeclared type "SpringImageView"

am really new to swift so what shall i do? please help

**Comment by schneiderandre** [comment]
If you have already included the Spring framework, try to write

`import Spring`

at the top of the Swift file where you want to use the `SpringImageView` :+1:

**Comment by oshiltawi** [comment]
i added import Spring and still getting the error..

i only moved the spring file to my project and i didnt add anything.. am i missing something?

**Comment by MengTo** [comment]
Please make sure to select Create groups and copy items if needed when dropping the Spring folder.




Thanks! Meng

**Comment by oshiltawi** [comment]
thank you allot! 1 more thing my image doesn't animate do i have to write some codes? or i can just use spring image view to animate it

**Comment by MengTo** [comment]
In storyboard make sure to enable auto start. In code, use animate()




Thanks! Meng

**Comment by oshiltawi** [comment]
i know i am a pain.. am really sorry its showing another error
http://i.imgur.com/FucacJr.png

**Comment by schneiderandre** [comment]
EXC_BAD_ACCESS usually means, that an object is not initialised or already released.

**Comment by oshiltawi** [comment]
thanks for your reply but i dont know what to do

**Comment by schneiderandre** [comment]
That's hard to tell without seeing the code. It can be nearly everything and isn't directly related to the Spring framework.

**Comment by oshiltawi** [comment]
http://i.imgur.com/lmFfes9.png

**Comment by schneiderandre** [comment]
Maybe your SpringImageView is not connected to the Storyboard.

**Comment by oshiltawi** [comment]
hmm if you would like to tell me the solution it will be amazing.
thanks

**Comment by oshiltawi** [comment]
anyone?

**Comment by schneiderandre** [comment]
Since the initial issue seems to be solved, I'll close it.
If you have any other issues related to the Spring framework, please let us know :+1:
