### ISSUE TITLE
Unable to enter decimals in Spring Image View

### ISSUE THREAD

**Issue by kktay281** [MengTo/Spring#83]
Hi guys,
I am not able to enter decimals in the attributes inspector of Spring.
It is only accepting whole numbers. Any idea why?
In the video demo. MengTo shows entering of decimal number in force, scale etc. but I am not able to do that.
I am using Xcode 6.4

Look forwards to some advice.

Regards
Steven

**Comment by MengTo** [comment]
I believe that in some keyboard languages, you need to enter a comma instead of a dot.



Thanks! Meng

**Comment by kktay281** [comment]
Thanks for the Tips Meng.
Indeed it is due to the languages. I have US keyboard setup but the region was Netherland and this automatically set the decimal and comma according to the local standard here.
