### ISSUE TITLE
Transition question

### ISSUE THREAD

**Issue by LightD** [MengTo/Spring#84]
How do I use `TransitionManager` or `TransitionZoom` classes that are declared in the framework? there isn't any example anywhere and I think it would be really helpful, but I'm very not sure how to use it, is there an example that I can find somewhere, or can someone show an example?

**Comment by schneiderandre** [comment]
These Transition Managers are not used in the Spring example project, you are right.

1. You need a stored property in your View Controller
 * `private let transitionManager = TransitionManager()`
2. Override the `prepareForSegue(segue: UIStoryboardSegue, sender: AnyObject?)` method in your View Controller and assign the property to your second View Controller.
 * `secondViewController.transitioningDelegate = transitionManager`

You can find an implementation of the TransitionManager in [DesignerNewsApp](https://github.com/MengTo/DesignerNewsApp/blob/master/DesignerNewsApp/StoriesTableViewController.swift).

Hope this helps!

**Comment by kiwo12345** [comment]
@schneiderandre does this only work on modal VC's ?
