### ISSUE TITLE
Need a brief explanation of those 4 functions:animateTo, animateNext, etc

### ISSUE THREAD

**Issue by dimefim** [MengTo/Spring#89]
I am new to this framework and can't understand what those functions do. I do understand `animate` and `animateNext:(void(^)(void))completion`. But could somebody give more details on these and two others? For instance, I need to animate a transition between 2 images in `SpringImageView`. What is the sequence of method calls? And when should i assign a new image? Thanks!

```   
        imageView.animation = @"fadeOut";
        imageView.curve = @"easeInOut";
        imageView.duration = 0.5;
        imageView.damping = 0.95;
        [imageView animateToNext:^{
            imageView.image = [UIImage imageWithCGImage:originalImageRef];
            NSString *direction;
            if(swipeRecognizer.direction == UISwipeGestureRecognizerDirectionLeft){
                direction = @"fadeInLeft";
            }
            else direction = @"fadeInRight";
            imageView.animation = direction;
            imageView.curve = @"easeInOut";
            imageView.duration = 1.0;
            imageView.damping = 0.95;
            [imageView animate];
        }];
```
I receive EXC_BAD_ACCESS at `imageView.image`

**Comment by dimefim** [comment]
Solved problem with bad access but still need method definitions

**Comment by lastMove** [comment]
animateTo do the animateTo in the opposite way of animate
You can by example "slideLeft" with animate: it will make the view come on the screen (from outside by the left).
If you make a "slideLeft" with animateTo: it will make the view go from the screen to outside.

**Comment by dimefim** [comment]
@lastMove. Thanks!
