### ISSUE TITLE
swift2 branch - Will not build for iOS 7 Xcode 7 beta 4

### ISSUE THREAD

**Issue by matthewcarlreetz** [MengTo/Spring#90]
I get lots of errors when building with XCode 7 beta 4 for iOS 7.  Is iOS 7 no longer supported?
<img width="271" alt="screen shot 2015-07-24 at 9 02 30 pm" src="https://cloud.githubusercontent.com/assets/1760821/8887436/9a6f1cf6-3247-11e5-996b-ffd41a27b6aa.png">

**Comment by schneiderandre** [comment]
@matthewcarlreetz, right. We have to support dynamic frameworks, which only work on 8.x. This is also a requirement to use CocoaPods, see #50.
