### ISSUE TITLE
SpringAnimation for OC lover

### ISSUE THREAD

**Issue by LawrenceHan** [MengTo/Spring#94]
## Reason
The SpringAnimation.swift doesn't support for objective-c.

## Resolution
Create a OC model that have same function as SpringAnimation.

> I bought the book BTW :DDD

**Comment by schneiderandre** [comment]
Hey @LawrenceHan, thanks for your suggestion and the Pull Request. :+1: 
I had a very similar issue a few days ago (#72) and struggled to close it. Now I have to admit that Obj-C is used more often than expected :smile:.
I would not recommend to duplicate code just to support Obj-C. I considered to remove the top-level functions and add them to a Class, but that would break API compatibility with previous Spring versions.

**Comment by LawrenceHan** [comment]
@schneiderandre I would drop Obj-C right now if our app started to use swift as main language. :smile: 
Spring is one of the most popular swift animation tool. So I would suggest to tell those Obj-C users to copy my code as a temporary workaround. (maybe put it in ReadME?)

And you may close this issue if you want.

**Comment by schneiderandre** [comment]
Haha, I know the feeling :joy:. I'm not sure if we really should close it, I'm sure there are others in the exact same position as you.
How does that sound: I'll do a feature branch to solve this without adding too much duplicate code and we can take a look if it works seamlessly with Obj-C.

**Comment by LawrenceHan** [comment]
Sounds perfect, please do it :+1:

**Comment by schneiderandre** [comment]
@LawrenceHan here is my solution #97.

**Comment by schneiderandre** [comment]
Okay, I merged this version. Have fun using it in Objective-C :smile:
